Fix compilation of benchmarks
Cargo was blocking compilation from macros.
```
error[E0658]: `macro` is experimental (see issue #39412)
 --> lib\benches\format-routing.rs:8:1
```
Also fixed warning about unused imports caused by
b8ba7b855f28be1f17bd65b35dd8597d368369ff
As well as unused variable a (fixed by giving an underscore name)

Unless I'm mistaken, these changes should not affect the benchmarks meaningfully